### ISSUE TITLE
Umzug zu git.raumzeitlabor.org

### ISSUE THREAD

**Issue by heylix** [raumzeitlabor/rzl-tuwat-archiv#211]
Wir haben ein selfhosted Gitlab unter https://git.raumzeitlabor.org – warum haben wir das Tuwat und alle anderen Repositories dann hier?

Außerdem gibt's noch https://gitlab.com/raumzeitlabor, welches einen (veralteten?) Mirror von den Github-Repositories beinhaltet. Warum?

ping @uwap

**Comment by heylix** [comment]
Außerdem hat Gitlab noch ein [sehr gutes](https://www.perforce.com/blog/vcs/comparison-of-git-powered-wikis-in-cloud-based-scm-tools) Wiki, mit dem man das wiki.raumzeitlabor.org ersetzen könnte. Man könnte dort auch Teams anlegen, Issues verwalten, kommunizieren etc. – würde also gleich mehrere Dienste ersetzen können.

**Comment by tabascoeye** [comment]
das lokal gehostete git enthält hauptsächlich zweierlei Repos:
* Vereinsverwaltung (und damit persönliche Daten). Liegt da wegen DSGVO
* Laser/Stick/Plotter repo mit Logos und ähnlichem Material, welches wir nicht einfach öffentlich zugänglich machen können/wollen wegen copyright foo

Der Rest ist grundsätzlich komplett hier bei github.
Wer den mirror auf gitlab.com betreut weiß ich nicht. Ich fürchte der kann weg?

**Comment by uwap** [comment]
Man könnte auch mal überlegen welcher der Github Reps wir umziehen könnten. Unabhängig davon: Falls wir dinge ins Gitlab umziehen sollten, müssen wir unbedingt auch die Resourcen für Neulinge überarebiten, da die ins tuwat etc. verweisen.

Ich wäre ja ehrlich gesagt auch für ein RZL LDAP, der über die Benutzerdb verwaltet wird oder so. Dann könnte man sich mit den BenutzerDB Daten im Gitlab einloggen.

**Comment by heylix** [comment]
Umzug hat stattgefunden:

https://git.raumzeitlabor.org/rzl/tuwat
